python3 scripts/bert_coref.py -m train -w models/crossval/0.model -t data/litbank_tenfold_splits/0/train.conll -v data/litbank_tenfold_splits/0/dev.conll -o preds/crossval/0.dev.pred -s reference-coreference-scorers/scorer.pl> logs/crossval/0.log 2>&1
python3 scripts/bert_coref.py -m train -w models/crossval/1.model -t data/litbank_tenfold_splits/1/train.conll -v data/litbank_tenfold_splits/1/dev.conll -o preds/crossval/1.dev.pred -s reference-coreference-scorers/scorer.pl> logs/crossval/1.log 2>&1
python3 scripts/bert_coref.py -m train -w models/crossval/2.model -t data/litbank_tenfold_splits/2/train.conll -v data/litbank_tenfold_splits/2/dev.conll -o preds/crossval/2.dev.pred -s reference-coreference-scorers/scorer.pl> logs/crossval/2.log 2>&1
python3 scripts/bert_coref.py -m train -w models/crossval/3.model -t data/litbank_tenfold_splits/3/train.conll -v data/litbank_tenfold_splits/3/dev.conll -o preds/crossval/3.dev.pred -s reference-coreference-scorers/scorer.pl> logs/crossval/3.log 2>&1
python3 scripts/bert_coref.py -m train -w models/crossval/4.model -t data/litbank_tenfold_splits/4/train.conll -v data/litbank_tenfold_splits/4/dev.conll -o preds/crossval/4.dev.pred -s reference-coreference-scorers/scorer.pl> logs/crossval/4.log 2>&1
python3 scripts/bert_coref.py -m train -w models/crossval/5.model -t data/litbank_tenfold_splits/5/train.conll -v data/litbank_tenfold_splits/5/dev.conll -o preds/crossval/5.dev.pred -s reference-coreference-scorers/scorer.pl> logs/crossval/5.log 2>&1
python3 scripts/bert_coref.py -m train -w models/crossval/6.model -t data/litbank_tenfold_splits/6/train.conll -v data/litbank_tenfold_splits/6/dev.conll -o preds/crossval/6.dev.pred -s reference-coreference-scorers/scorer.pl> logs/crossval/6.log 2>&1
python3 scripts/bert_coref.py -m train -w models/crossval/7.model -t data/litbank_tenfold_splits/7/train.conll -v data/litbank_tenfold_splits/7/dev.conll -o preds/crossval/7.dev.pred -s reference-coreference-scorers/scorer.pl> logs/crossval/7.log 2>&1
python3 scripts/bert_coref.py -m train -w models/crossval/8.model -t data/litbank_tenfold_splits/8/train.conll -v data/litbank_tenfold_splits/8/dev.conll -o preds/crossval/8.dev.pred -s reference-coreference-scorers/scorer.pl> logs/crossval/8.log 2>&1
python3 scripts/bert_coref.py -m train -w models/crossval/9.model -t data/litbank_tenfold_splits/9/train.conll -v data/litbank_tenfold_splits/9/dev.conll -o preds/crossval/9.dev.pred -s reference-coreference-scorers/scorer.pl> logs/crossval/9.log 2>&1


python3 scripts/bert_coref.py -m train -w models_relate/crossval/0.model -t data/litbank_tenfold_splits/0/train.conll -v data/litbank_tenfold_splits/0/dev.conll -o preds_relate/crossval/0.dev.pred -s reference-coreference-scorers/scorer.pl> logs_relate/crossval/0.log 2>&1